import ProjectLayout, { Paragraph, Figure, FigureGrid, Table } from '../../../../components/ProjectLayout/ProjectLayout'

export default function DukeAeroLiquids2526() {
  return (
    <ProjectLayout
      category="Hardware"
      categoryHref="/hardware"
      title="DukeAERO Liquids 25-26"
      subtitle="Modeling propellant pressure losses and mass flow on DukeAERO's liquid propulsion subteam for the 2025-26 school year"
    >
      <Paragraph>
        For liquid propulsion I developed a simulation in Python to find propellant pressure
        losses and mass flow rates through our piping prior to being injected into the combustion
        chamber. We are developing our team's first liquid engine, using kerosene as the fuel
        and nitrous oxide as the oxidizer. The numbers generated by the simulation can be compared
        to the water cold flow tests, and can be used to predict the performance when we switch
        to kerosene.
      </Paragraph>
      <Paragraph>
        To run the simulation, relvant parameters, such as the injector specifications, propellant
        characteristics, and pipe elements and their dimensions, as well as the tank pressure
        and ambient chamber pressure are input (Figure 2-1). The simulation is then run with
        a specified maximum number of iterations, and it will iterate until the solution has
        sufficiently converged. Once solved, the results will print to the console (Figure 2-2).
      </Paragraph>

      <FigureGrid>
        <Figure src="/hardware/2025/aero/imgs/setup.png" caption="Figure 2-1. Example simulation input parameters" />
        <Figure src="/hardware/2025/aero/imgs/solution.png" caption="Figure 2-2. Results of the simulation" />
      </FigureGrid>

      <Paragraph>
        The simulation works by calculating the pressure losses through each element, and comparing
        the mass flow through the flowmeter and through the injector. The simulation will iteratively
        vary the mass flow rate of the propellant until continuity is maintained throughout
        the system. By default it checks for a mass flow difference of less than 1e-6 kg/s,
        but a different threshold can be sent as an argument to the solve function.
      </Paragraph>
      <Paragraph>
        By tuning the characteristics of the piping elements, the simulation can be made to closely
        approximate the results of actual testing (Table 2-1).
      </Paragraph>

      <Table
        headers={['Run', 'FM Upstream (PSI)', 'FM Loss (PSI)', 'FM Mass Flow (kg/s)', 'INJ Loss (PSI)', 'INJ Mass Flow (kg/s)']}
        rows={[
          ['11/22/25', '624.7', '168.1', '0.260', '283.7', '0.260'],
          ['Sim', '648.9', '166.0', '0.262', '256.1', '0.262'],
        ]}
        caption="Table 2-1: Values from a cold flow on 11/22/25 and a simulation run measured at the flowmeter (FM) and injector (INJ) for an 850 PSI tank pressure"
      />
    </ProjectLayout>
  )
}
