import ProjectLayout, { Heading, Paragraph, Video, CodeBlock } from '../../../../components/ProjectLayout/ProjectLayout'

export default function Electromagnetism() {
  return (
    <ProjectLayout
      category="Software"
      categoryHref="/software"
      title="Electromagnetism"
      subtitle="Simulation of electric and magnetic fields written in Julia"
    >
      <Heading>Overview</Heading>
      <Paragraph>
        This project simulates the electric and magnetic fields generated by moving point charges,
        written in <a href="https://julialang.org/" target="_blank" rel="noreferrer">Julia</a> using{' '}
        <a href="https://makie.org/website/" target="_blank" rel="noreferrer">Makie.jl</a> for plotting
        (<a href="https://github.com/echotops/electromagnetism" target="_blank" rel="noreferrer">source on GitHub</a>).
        There are two simulation methods included, but the pipeline for each is the same: each
        simulation is run with a given timestep, iteration count, and point charge generating
        function, storing the results to disk, and a separate plotting script then generates a
        video animating the motion of the charges and fields (Figure 1-1).
      </Paragraph>

      <Video
        src="/software/projects/electromagnetism/vids/dipole.mp4"
        caption="Figure 1-1. One positive and one negative charge oscillating"
      />

      <Paragraph>
        The first method, <code>jefimenko-feynman.jl</code>, uses the Jefimenko-Feynman
        (Heaviside-Feynman) equations to find the electric and magnetic fields directly from the
        positions of the point charges. The second, <code>causal-rk4.jl</code>, uses a Runge-Kutta
        4 solver to iterate an initial electric field forward using Maxwell's equations — here the
        electric field can be seen as directly causing the magnetic field, whereas the
        Jefimenko-Feynman method instead treats both fields as being generated directly by the
        charges and currents.
      </Paragraph>

      <Heading>Point Charge Generation</Heading>
      <Paragraph>
        Each point charge is generated by a function, with a position parametrized as a function
        of time along with a fixed charge. The position function can be edited to trace out a wide
        range of parametric shapes — the function below generates 32 point charges moving around a
        toroid.
      </Paragraph>

      <CodeBlock>{`function getPointCharges()
    function toroid(t, ϕ)
        w = 0.5
        r = 2.5
        k = 16
        s = 0.075 * c * t + ϕ
        return [cos(s) * (r + w * sin(k * s)),
                sin(s) * (r + w * sin(k * s)),
                w * cos(k * s)]
    end
    return [PointCharge(t -> toroid(t, ϕ), 1) for ϕ in 0:π/16:31π/16]
end`}</CodeBlock>

      <Video
        src="/software/projects/electromagnetism/vids/toroid32.mp4"
        caption="Figure 2-1. Magnetic field generated by 32 point charges moving in a toroid"
      />

      <Paragraph>
        Increasing the charge count to 64 makes the structure more apparent (Figure 2-2). Note
        that the magnetic field inside the torus points along the toroidal direction, while at the
        center of the torus the field points in the negative z direction.
      </Paragraph>

      <Video
        src="/software/projects/electromagnetism/vids/toroid.mp4"
        caption="Figure 2-2. Magnetic field generated by 64 point charges moving in a toroid"
      />

      <Paragraph>
        Here 4 point charges rotate in a circle (Figure 2-3) — the magnetic field at the center is
        comparatively strong and points in the negative z direction.
      </Paragraph>

      <Video
        src="/software/projects/electromagnetism/vids/donut.mp4"
        caption="Figure 2-3. Magnetic field generated by 4 point charges moving in a circle"
      />
    </ProjectLayout>
  )
}
